version: '3.7'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./rules/:/etc/prometheus/rules/:ro
    ports:
      - "9090:9090"
    depends_on:
      - blackbox

  blackbox:
    image: prom/blackbox-exporter:latest
    container_name: blackbox
    volumes:
      # Mount your host blackbox.yml into the container’s config directory
      - ./blackbox.yml:/etc/blackbox_exporter/blackbox.yml:ro
    command:
      - '--config.file=/etc/blackbox_exporter/blackbox.yml'
    ports:
      - "9115:9115"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    # (optional) mount a custom provisioning folder:
    # volumes:
    #   - ./grafana/provisioning:/etc/grafana/provisioning:ro