services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest #latest statick version or "latest" to run latest image
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TOKEN}