version: "3.8"

services:
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    # container_name: php-fpm   # optional; container_name can be omitted for portability
    volumes:
      - ./www:/var/www/html:cached
      - vendor_data:/var/www/html/vendor
    env_file:
      - .env
    networks:
      - appnet

  nginx:
    image: nginx:stable
    container_name: nginx
    depends_on:
      - php
    ports:
      - "5500:80"
    volumes:
      - ./www:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - appnet

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - appnet

volumes:
  db_data:
  vendor_data:

networks:
  appnet:
    driver: bridge
