services:
  mc:
    container_name: minecraft
    image: itzg/minecraft-server:java21-jdk
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
    volumes:
      - ./data:/data
